CREATE TABLE importacao_nota_fiscal_detalhe (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    notafiscal_id BIGINT NOT NULL,
    produto_item INT(11)  NOT NULL,
    produto_codigo BIGINT NOT NULL,
    produto_ean VARCHAR(20),
    produto_descricao VARCHAR(80),
    produto_ncm VARCHAR(10),
    produto_cfop VARCHAR(5),
    produto_unidade VARCHAR(20),
    produto_quantidade DECIMAL(15,3) NOT NULL,
    produto_valor_unitario DECIMAL(18,6) NOT NULL,
    produto_valor_total DECIMAL(18,6) NOT NULL,
    imposto_icms_cst VARCHAR(10),
    imposto_icms_origem VARCHAR(15),
    imposto_icms_base_calculo DECIMAL(18,6) DEFAULT 0,
    imposto_icms_aliquota DECIMAL(18,6) DEFAULT 0,
    imposto_icms_valor DECIMAL(18,6) DEFAULT 0,
    imposto_icms_percentual_reducao DECIMAL(18,6) DEFAULT 0,
    imposto_icms_mva_st DECIMAL(18,6) DEFAULT 0,
    imposto_icms_base_calculo_st DECIMAL(18,6) DEFAULT 0,
    imposto_icms_aliquota_st DECIMAL(18,6) DEFAULT 0,
    imposto_icms_valor_st DECIMAL(18,6) DEFAULT 0,
    imposto_icms_percentual_reducao_st DECIMAL(18,6) DEFAULT 0,
    imposto_ipi_cst VARCHAR(10),
    imposto_ipi_base_calculo DECIMAL(18,6) DEFAULT 0,
    imposto_ipi_aliquota DECIMAL(18,6) DEFAULT 0,
    imposto_ipi_valor DECIMAL(18,6) DEFAULT 0,
    imposto_pis_cst VARCHAR(10),
    imposto_pis_base_calculo DECIMAL(18,6) DEFAULT 0,
    imposto_pis_aliquota DECIMAL(18,6) DEFAULT 0,
    imposto_pis_valor DECIMAL(18,6) DEFAULT 0,
    imposto_cofins_cst VARCHAR(10),
    imposto_cofins_base_calculo DECIMAL(18,6) DEFAULT 0,
    imposto_cofins_aliquota DECIMAL(18,6) DEFAULT 0,
    imposto_cofins_valor DECIMAL(18,6) DEFAULT 0,
    imposto_valor_aprox_tributos DECIMAL(18,6) DEFAULT 0,
    CONSTRAINT fk_detalhe_notafiscal_id 
        FOREIGN KEY (notafiscal_id)  REFERENCES importacao_nota_fiscal (id),
    CONSTRAINT uc_detalhe_notafiscal_item_produto 
        UNIQUE (notafiscal_id, produto_item, produto_codigo)        
);
